// Copyright 2021 Danny Hermes
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package booksprovider

import (
	"github.com/google/uuid"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"

	"github.com/dhermes/example-terraform-provider/pkg/terraform"
)

// NewDataSourceAuthor creates a new `DataSourceAuthor` from a Terraform
// resource data struct.
func NewDataSourceAuthor(d *schema.ResourceData) (*DataSourceAuthor, error) {
	dsa := DataSourceAuthor{d: d}
	err := dsa.Populate()
	if err != nil {
		return nil, err
	}

	return &dsa, nil
}

// GetFirstName is a value accessor for a pointer field; a safe dereference.
// (The goal is to make code that can be autogenerated.)
func (dsa *DataSourceAuthor) GetFirstName() string {
	dsa.mutex.RLock()
	defer dsa.mutex.RUnlock()

	if dsa.FirstName == nil {
		return ""
	}
	return *dsa.FirstName
}

// GetLastName is a value accessor for a pointer field; a safe dereference.
// (The goal is to make code that can be autogenerated.)
func (dsa *DataSourceAuthor) GetLastName() string {
	dsa.mutex.RLock()
	defer dsa.mutex.RUnlock()

	if dsa.LastName == nil {
		return ""
	}
	return *dsa.LastName
}

// GetBookCount is a value accessor for a pointer field; a safe dereference.
// (The goal is to make code that can be autogenerated.)
func (dsa *DataSourceAuthor) GetBookCount() int {
	dsa.mutex.RLock()
	defer dsa.mutex.RUnlock()

	if dsa.BookCount == nil {
		return 0
	}
	return *dsa.BookCount
}

// GetID is a value accessor for a pointer field; a safe dereference.
// (The goal is to make code that can be autogenerated.)
func (dsa *DataSourceAuthor) GetID() uuid.UUID {
	dsa.mutex.RLock()
	defer dsa.mutex.RUnlock()

	if dsa.ID == nil {
		return uuid.Nil
	}
	return *dsa.ID
}

// Populate populates the fields in this struct based on the `terraform`
// struct tags. (The goal is to make code that can be autogenerated.)
func (dsa *DataSourceAuthor) Populate() error {
	dsa.mutex.Lock()
	defer dsa.mutex.Unlock()

	var err error

	// first_name | string | required
	firstName, ok := dsa.d.Get("first_name").(string)
	if !ok {
		err = terraform.DiagnosticError{
			Summary: "Could not determine author first name",
			Detail:  "Invalid first name parameter type",
		}
		return err
	}

	// last_name | string | required
	lastName, ok := dsa.d.Get("last_name").(string)
	if !ok {
		err = terraform.DiagnosticError{
			Summary: "Could not determine author last name",
			Detail:  "Invalid last name parameter type",
		}
		return err
	}

	// book_count | int | computed
	bookCount := dsa.BookCount
	bookCountInterface := dsa.d.Get("book_count")
	if bookCountInterface != nil {
		bc, ok := bookCountInterface.(int)
		if !ok {
			err = terraform.DiagnosticError{
				Summary: "Could not determine author book count",
				Detail:  "Invalid book count parameter type",
			}
			return err
		}
		bookCount = &bc
	}

	// id | uuid.UUID->string | computed
	idStr := dsa.d.Id()
	id := dsa.ID
	if idStr != "" {
		parsed, err := idFromString(idStr, "ID")
		if err != nil {
			return err
		}
		id = &parsed
	}

	// Only populate fields after all parsing is complete without error.
	dsa.FirstName = &firstName
	dsa.LastName = &lastName
	dsa.BookCount = bookCount
	dsa.ID = id
	return nil
}

// Persist writes back fields in this struct to the Terraform resource data
// struct based on the `terraform` struct tags. (The goal is to make code that
// can be autogenerated.)
//
// NOTE: This method only takes a read lock for the exported fields,
//       `FirstName`, `LastName`, `BookCount` and `ID`. This method does do
//       some "writes" to `ra.d` but the lock is not intended to make
//       `schema.ResourceData` concurrency-safe (it is already via
//       `MapFieldWriter`).
func (dsa *DataSourceAuthor) Persist() error {
	dsa.mutex.RLock()
	defer dsa.mutex.RUnlock()

	if dsa.FirstName != nil {
		err := dsa.d.Set("first_name", *dsa.FirstName)
		if err != nil {
			return err
		}
	}

	if dsa.LastName != nil {
		err := dsa.d.Set("last_name", *dsa.LastName)
		if err != nil {
			return err
		}
	}

	if dsa.BookCount != nil {
		err := dsa.d.Set("book_count", *dsa.BookCount)
		if err != nil {
			return err
		}
	}

	if dsa.ID != nil {
		dsa.d.SetId(dsa.ID.String())
	}

	return nil
}

// Schema produces the Terraform Schema map. (The goal is to make code that
// can be autogenerated.)
func (*DataSourceAuthor) Schema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		// first_name | string | required
		"first_name": {
			Type:     schema.TypeString,
			Required: true,
		},
		// last_name | string | required
		"last_name": {
			Type:     schema.TypeString,
			Required: true,
		},
		// book_count | int | computed
		"book_count": {
			Type:     schema.TypeInt,
			Computed: true,
		},
		// id | uuid.UUID->string | computed
		"id": {
			Type:     schema.TypeString,
			Computed: true,
		},
	}
}
